### ISSUE TITLE
Apt7 1.7.2 Not Found

### ISSUE THREAD

**Issue by berkayaksoy** [Diatrus/sileo-installer#1]
Library not found. Not install Sileo.

**Comment by Diatrus** [comment]
Fixed in 0.9

**Comment by lordiphie** [comment]
dpkg-deb error: /tmp/apt7-lib_1.7.2_iphoneos-arm.deb is not a debian format archive

Error I got
iPhone X
iOS 12.1.1

Still giving the Same error while install sileo

**Comment by Diatrus** [comment]
@lordiphie you didn’t update to 0.9
